### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by Gracccce** [TomasAndersonFang/SANCS#1]
Since the code snippets are split into method name , API and tokens sequences, could you offer the code used to preprocess the data?

**Comment by TomasAndersonFang** [comment]
I use the pre-processed dataset shared by the author of DeepCS. Although I
asked he for the raw dataset, he doesn’t provide.

在 2021年5月7日星期五，Gracccce ***@***.***> 写道：

**Comment by ChengDale** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './model_save/joint_embed_model.h5'
